typedef enum NodeType {
  NODE_PRIMITIVE_NUMBER,
  NODE_PRIMITIVE_STRING,
  NODE_PRIMITIVE_BOOLEAN,
  NODE_PRIMITIVE_NULL,
  NODE_PRIMITIVE_UNDEFINED,
  NODE_IDENTIFIER,
  NODE_BINARY_OPERATOR,
  NODE_UNARY_OPERATOR,
  NODE_STATEMENT_RETURN,
  NODE_STATEMENT_IF,
  NODE_VAR_DECLARATION,
  NODE_VAR_ASSIGNMENT,
  NODE_FUNCTION_CALL,
  NODE_FUNCTION_DECLARATION,
  NODE_PROGRAM,
  NODE_STATEMENT_LIST,
} NodeType;

typedef struct Node {
  NodeType type;
  char *value;
  struct Node **args;
  struct Node **children;
} Node;

Node* parse(Token *token);
void node_pp(Node *node);
